### ISSUE TITLE
GraphQL Playground links not working

### ISSUE THREAD

**Issue by Modjo** [MoonHighway/learning-graphql#13]
Hi Alex, Hi Eve,

I've started your book recently (Kindle version), everything was great so far but I just noticed that the links to GraphQL Playground example code were always redirected to [this link](https://www.graphqlbin.com/v2/new)
Unfortunately it prevents me working with the example code.
Is there a way to fix it ?

Thanks and congrats for the book, I am really enjoying it so far !

**Comment by eveporcello** [comment]
Thanks so much for bringing that to my attention. I assume that you're talking about the Union and Interface examples. The good news is it looks like there are only two spots where we use GraphQL bin. The bad news is - something in the last couple weeks has broken those links with GraphQL bin!

I will get in touch with O'Reilly about removing those links from the book. In the meantime, I've updated the links in this repo and you can find them here.

* [Union Types](https://launchpad.graphql.com/r94qxj5q4n): Union types sample 
* [Interfaces](https://launchpad.graphql.com/j8r375km3p): Interfaces sample 

Feel free to email with any other questions that come up: [eve@moonhighway.com](mailto:eve@moonhighway.com).

**Comment by melo0187** [comment]
@eveporcello I got the book just yesterday and enjoy it very much.

I just wanted to let you know that the GraphQL bin links seem to work again, at least the two you mentioned.
However the issue is not really solved, because the GraphQL endpoints those GraphQL Playgrounds point to are simply not available. Requesting them returns http 502/503.
Sadly this is true for the alternative Apollo Launchpad links you provided, too.

**Comment by mikhailbalin** [comment]
@eveporcello @melo0187 Hi, us I understand Launchpad discontinue their service, so there are two temporary links for the examples in Chapter 3:

[Interfaces sample ](https://p79k2n635x.sse.codesandbox.io)– editor https://codesandbox.io/s/p79k2n635x?fontsize=14
[Union types sample](https://72kppqr7kq.sse.codesandbox.io/) – editor https://codesandbox.io/s/72kppqr7kq?fontsize=14

Google play books also needs to be updated.
