### ISSUE TITLE
[ts] Type 'string' is not assignable to type 'DocumentNode | DocumentNode[]'.

### ISSUE THREAD

**Issue by aadrew** [MoonHighway/learning-graphql#15]
I'm guessing this is due to changes in `apollo-server-express` since you published?  If I google, I can find several workarounds, but I am interested in how you would solve this.  Thanks!

https://github.com/MoonHighway/learning-graphql/blob/9cbe6b2c0bcbef3ab346643434c4f8c8df3c46de/chapter-05/photo-share-api/index.js#L32

**Comment by aadrew** [comment]
Thank you, @eveporcello.  The workaround I found was exactly your solution.  Sorry I didn't update this issue earlier.  Thank you for your response.  It's good to know we came to the same solution.

**Comment by eveporcello** [comment]
awesome! glad that worked!
