### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by DevJoseWeb** [MoonHighway/learning-graphql#20]
Adorei o livro, sentir falta somente, de uma api usando java, ja que java e a linguagem mais usada no mundo para escrever api REST, no proximo livro vai contemplar isso ,,,,

Obrigado.,..

**Comment by MoonTahoe** [comment]
Eu uso continuamente JavaScript por mais de 20 anos, mas eu não uso Java há muito tempo, então eu não seria a melhor pessoa para escrever esse livro.

Confira este tutorial:

[How to GraphQL JAVA](https://www.howtographql.com/graphql-java/0-introduction/)
