### ISSUE TITLE
Chapter 6: Apollo Client with React and Caching -> why use restore instead of await persistCache?

### ISSUE THREAD

**Issue by melo0187** [MoonHighway/learning-graphql#22]
Chapter 6 does praise Apollo Client for providing a cache (among many other things). However, the suggested way of using apollo-boost with react-apollo does not make proper use of the cache.

When following along with chapter 6 all the way to the end of the paragraph about react-apollo's Query component I noticed that the application does not showcase the caching mechanism suggested by the book. Reloading the application will always cause a POST request to be sent to the GraphQL API.

**Comment by melo0187** [comment]
Ok I have to correct myself.
I learned that my expectation was wrong. Without apollo-cache-persist there is no reason to expect the cache to be present on a page reload. You do explain this further down the way in chapter 6.

What I'm still wondering about:
You do use `persistCache()` from `apollo-cache-persist`, but this method returns a promise and is actually already trying to restore the cache.
Why don't  you `await` for  `persistCache()`'s promise to resolve before rendering instead of calling `restore` yourself?

**Comment by MoonTahoe** [comment]
Sounds like a better solution.
